export const mockData = {
  tables: [
    {
      name: 'orders',
      type: 'table',
      columns: ['ORDER_ID', 'CUSTOMER_ID', 'ORDER_TOTAL', 'SALE_REP_ID'],
    },
    // {
    //   name: 'INSERT-SELECT-1',
    //   type: 'select',
    //   columns: ['oid', 'ottl', 'sid', 'cid', 'cl', 'cem'],
    // },
    {
      name: 'customer',
      type: 'table',
      columns: ['CREDIT_LIMIT', 'CUST_EMAIL'],
    },
    //   {
    //     name: 'large_orders',
    //     type: 'table',
    //     columns: ['OID', 'OTTL', 'SID', 'CID', 'CL', 'CEM'],
    //   },
    //   {
    //     name: 'medium_orders',
    //     type: 'table',
    //     columns: ['OID', 'OTTL', 'SID', 'CID', 'CL', 'CEM'],
    //   },
    //   {
    //     name: 'small_orders',
    //     type: 'table',
    //     columns: ['OID', 'OTTL', 'SID', 'CID', 'CL', 'CEM'],
    //   },
    //   {
    //     name: 'special_orders',
    //     type: 'table',
    //     columns: ['OID', 'OTTL', 'SID', 'CID', 'CL', 'CEM'],
    //   },
    // ],
    // relationships: [
    //   {
    //     parentTable: 'orders',
    //     parentColumn: 'ORDER_ID',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'oid',
    //   },
    //   {
    //     parentTable: 'orders',
    //     parentColumn: 'CUSTOMER_ID',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'cid',
    //   },
    //   {
    //     parentTable: 'orders',
    //     parentColumn: 'ORDER_TOTAL',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'ottl',
    //   },
    //   {
    //     parentTable: 'orders',
    //     parentColumn: 'SALE_REP_ID',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'sid',
    //   },
    //   {
    //     parentTable: 'customer',
    //     parentColumn: 'CREDIT_LIMIT',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'cl',
    //   },
    //   {
    //     parentTable: 'customer',
    //     parentColumn: 'CUST_EMAIL',
    //     childTable: 'INSERT-SELECT-1',
    //     childColumn: 'cem',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'oid',
    //     childTable: 'large_orders',
    //     childColumn: 'OID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'ottl',
    //     childTable: 'large_orders',
    //     childColumn: 'OTTL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'sid',
    //     childTable: 'large_orders',
    //     childColumn: 'SID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cid',
    //     childTable: 'large_orders',
    //     childColumn: 'CID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cl',
    //     childTable: 'large_orders',
    //     childColumn: 'CL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cem',
    //     childTable: 'large_orders',
    //     childColumn: 'CEM',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'oid',
    //     childTable: 'medium_orders',
    //     childColumn: 'OID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'ottl',
    //     childTable: 'medium_orders',
    //     childColumn: 'OTTL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'sid',
    //     childTable: 'medium_orders',
    //     childColumn: 'SID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cid',
    //     childTable: 'medium_orders',
    //     childColumn: 'CID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cl',
    //     childTable: 'medium_orders',
    //     childColumn: 'CL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cem',
    //     childTable: 'medium_orders',
    //     childColumn: 'CEM',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'oid',
    //     childTable: 'special_orders',
    //     childColumn: 'OID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'ottl',
    //     childTable: 'special_orders',
    //     childColumn: 'OTTL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'sid',
    //     childTable: 'special_orders',
    //     childColumn: 'SID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cid',
    //     childTable: 'special_orders',
    //     childColumn: 'CID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cl',
    //     childTable: 'special_orders',
    //     childColumn: 'CL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cem',
    //     childTable: 'special_orders',
    //     childColumn: 'CEM',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'oid',
    //     childTable: 'small_orders',
    //     childColumn: 'OID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'ottl',
    //     childTable: 'small_orders',
    //     childColumn: 'OTTL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'sid',
    //     childTable: 'small_orders',
    //     childColumn: 'SID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cid',
    //     childTable: 'small_orders',
    //     childColumn: 'CID',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cl',
    //     childTable: 'small_orders',
    //     childColumn: 'CL',
    //   },
    //   {
    //     parentTable: 'INSERT-SELECT-1',
    //     parentColumn: 'cem',
    //     childTable: 'small_orders',
    //     childColumn: 'CEM',
    //   },
  ],
};
