export const TYPE = [
  { value: 'CHAR' },
  { value: 'VARCHAR(255)' },
  { value: 'TINYTEXT' },
  { value: 'TEXT' },
  { value: 'BLOB' },
  { value: 'MEDIUMTEXT' },
  { value: 'MEDIUMBLOB' },
  { value: 'LONGTEXT' },
  { value: 'LONGBLOB' },
  { value: 'TINYINT' },
  { value: 'SMALLINT' },
  { value: 'MEDIUMINT' },
  { value: 'INT' },
  { value: 'BIGINT' },
  { value: 'FLOAT' },
  { value: 'DOUBLE' },
  { value: 'DECIMAL' },
  { value: 'DATE' },
  { value: 'DATETIME' },
  { value: 'TIMESTAMP' },
  { value: 'TIME' },
  { value: 'ENUM' },
  { value: 'SET' },
  { value: 'BOOLEAN' },
];
