export const TYPE = [
  { value: 'char' },
  { value: 'varchar(255)' },
  { value: 'tinytext' },
  { value: 'text' },
  { value: 'blob' },
  { value: 'mediumtext' },
  { value: 'mediumblob' },
  { value: 'longtext' },
  { value: 'longblob' },
  { value: 'tinyint' },
  { value: 'smallint' },
  { value: 'mediumint' },
  { value: 'int' },
  { value: 'bigint' },
  { value: 'float' },
  { value: 'double' },
  { value: 'decimal' },
  { value: 'date' },
  { value: 'datetime' },
  { value: 'timestamp' },
  { value: 'time' },
  { value: 'enum' },
  { value: 'set' },
  { value: 'boolean' },
  { value: 'string' },
];
